version: '3.3'

services:
  jenkins:
    build:
      context: .
      dockerfile: Jenkins.Dockerfile
    ports:
      - 8090:8080
    restart: always
    privileged: true
    volumes:
      - type: bind
        source: ./secrets/private
        target: /home/jenkins/.ssh/
        read_only: true